global_frame_id: 'map'
base_frame_id: 'base_footprint'

control_freq: 40                        # Hz
transform_timeout: 0.1                  # seconds
rob_dist_between_front_back_wh: 0.265   # meters
rob_dist_between_left_right_wh: 0.270   # meters